stable repo check (wip)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1276,6 +1276,161 @@ install-ubuntu-24.10-amd64:
   image: registry.nic.cz/labs/bird:ubuntu-24.10-amd64
 
 
+.install-stable-repo-rpm: &install-stable-repo-rpm
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now and no user or group bird exists
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: BIRD unexpectedly installed"
+        exit 1
+      fi
+      if id -g bird >/dev/null 2>&1; then
+        echo "Error: User group 'bird' exist before installation"
+        exit 1
+      fi
+      if id -u bird >/dev/null 2>&1; then
+        echo "Error: User 'bird' exist before installation"
+        exit 1
+      fi
+    - |
+      cat > /etc/yum.repo.d/bird.nic.cz.repo <<EOF
+      [bird]
+      name=bird (nic.cz)
+      baseurl=$REPOURL
+      enabled=1
+      EOF
+    - yum -y update
+    - yum -y install bird=3.1.4
+
+install-stable-repo-centos-7-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:centos-7-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/centos/7/amd64/x64_64
+
+install-stable-repo-centos-8-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:centos-8-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/centos/8/amd64/x64_64
+
+install-stable-repo-rocky-08-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:rocky-08-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/rocky/08/amd64/x64_64
+
+install-stable-repo-rocky-09-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:rocky-09-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/rocky/09/amd64/x64_64
+
+install-stable-repo-fedora-32-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-32-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/32/amd64/x64_64
+
+install-stable-repo-fedora-33-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-33-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/33/amd64/x64_64
+
+install-stable-repo-opensuse-15.0-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:opensuse-15.0-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/opensuse/15.0/amd64/x64_64
+
+install-stable-repo-opensuse-15.1-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:opensuse-15.1-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/opensuse/15.1/amd64/x64_64
+
+install-stable-repo-opensuse-15.2-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:opensuse-15.2-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/opensuse/15.2/amd64/x64_64
+
+install-stable-repo-opensuse-15.3-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:opensuse-15.3-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/opensuse/15.3/amd64/x64_64
+
+install-stable-repo-opensuse-15.4-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:opensuse-15.4-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/opensuse/15.4/amd64/x64_64
+
+install-stable-repo-opensuse-15.5-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:opensuse-15.5-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/opensuse/15.5/amd64/x64_64
+
+install-stable-repo-fedora-34-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-34-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/34/amd64/x64_64
+
+install-stable-repo-fedora-35-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-35-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/35/amd64/x64_64
+
+install-stable-repo-fedora-36-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-36-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/36/amd64/x64_64
+
+install-stable-repo-fedora-37-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-37-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/37/amd64/x64_64
+
+install-stable-repo-fedora-38-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-38-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/38/amd64/x64_64
+
+install-stable-repo-fedora-39-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-39-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/39/amd64/x64_64
+
+install-stable-repo-fedora-40-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-40-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/40/amd64/x64_64
+
+install-stable-repo-fedora-41-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-41-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/41/amd64/x64_64
+
+install-stable-repo-fedora-42-amd64:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:fedora-42-amd64
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/fedora/42/amd64/x64_64
+
+
 ###################################
 ## Non-linux build tests in QEMU ##
 ###################################
diff --git a/misc/gitlab/template.yml.j2 b/misc/gitlab/template.yml.j2
--- a/misc/gitlab/template.yml.j2
+++ b/misc/gitlab/template.yml.j2
@@ -368,6 +368,46 @@ install-{{ dist["name"] }}:
   image: registry.nic.cz/labs/bird:{{ dist["name"] }}
 {% endfor %}
 
+.install-stable-repo-rpm: &install-stable-repo-rpm
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now and no user or group bird exists
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: BIRD unexpectedly installed"
+        exit 1
+      fi
+      if id -g bird >/dev/null 2>&1; then
+        echo "Error: User group 'bird' exist before installation"
+        exit 1
+      fi
+      if id -u bird >/dev/null 2>&1; then
+        echo "Error: User 'bird' exist before installation"
+        exit 1
+      fi
+    - |
+      cat > /etc/yum.repo.d/bird.nic.cz.repo <<EOF
+      [bird]
+      name=bird (nic.cz)
+      baseurl=$REPOURL
+      enabled=1
+      EOF
+    - yum -y update
+    - yum -y install bird=3.1.4
+
+{%- for dist in distros %}
+{%- if dist["type"] == "pkg-rpm" or dist["type"] == "pkg-rpm-wa" %}
+
+install-stable-repo-{{ dist["name"] }}:
+  <<: *install-stable-repo-rpm
+  image: registry.nic.cz/labs/bird:{{ dist["name"] }}
+  variables:
+    REPOURL: http://pkg.labs.nic.cz/rpm/bird/{{ dist["name"].split("-") | join("/") }}/x64_64
+{%- endif %}
+{%- endfor %}
+
+
 ###################################
 ## Non-linux build tests in QEMU ##
 ###################################
