CI: Add package install tests.
We are checking that generated BIRD packages can be installed and run.
Communication between bird and birdc is also tested.

This fixes #202

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,6 +23,7 @@ stages:
   - image
   - build
   - pkg
+  - install
   - test
 
 ## Common rules
@@ -618,7 +619,6 @@ build-release:
     - if python3 -m venv venv; then . venv/bin/activate; fi
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.deb
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -636,7 +636,6 @@ build-release:
     - pip3 install beautifulsoup4==4.11.2
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.deb
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -648,7 +647,6 @@ build-release:
   script:
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.rpm
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -663,7 +661,6 @@ build-release:
     - pip3 install beautifulsoup4==4.11.2
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.rpm
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -928,6 +925,232 @@ pkg-ubuntu-24.10-amd64:
     - job: build-ubuntu-24.10-amd64
       artifacts: false
     - job: build-release
+  image: registry.nic.cz/labs/bird:ubuntu-24.10-amd64
+
+
+## Package installability checks
+
+.install-deb: &install-deb
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: bird unexpectedly installed"
+        exit 1
+      fi
+    # install packages
+    - find pkg/pkgs/ -type f -name '*.deb' '(' -ls -exec dpkg -i '{}' ';' ')'
+    # test that install is correct
+    - ./tools/test-install "$CI_COMMIT_MESSAGE"
+
+.install-rpm: &install-rpm
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: bird unexpectedly installed"
+        exit 1
+      fi
+    # install packages
+    - find pkg/pkgs/ -type f -name '*.rpm' '(' -ls -exec rpm -i '{}' ';' ')'
+    # test that install is correct
+    - ./tools/test-install "$CI_COMMIT_MESSAGE"
+
+
+install-centos-7-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-centos-7-amd64
+  image: registry.nic.cz/labs/bird:centos-7-amd64
+
+install-centos-8-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-centos-8-amd64
+  image: registry.nic.cz/labs/bird:centos-8-amd64
+
+install-fedora-32-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-32-amd64
+  image: registry.nic.cz/labs/bird:fedora-32-amd64
+
+install-fedora-33-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-33-amd64
+  image: registry.nic.cz/labs/bird:fedora-33-amd64
+
+install-opensuse-15.0-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-opensuse-15.0-amd64
+  image: registry.nic.cz/labs/bird:opensuse-15.0-amd64
+
+install-opensuse-15.1-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-opensuse-15.1-amd64
+  image: registry.nic.cz/labs/bird:opensuse-15.1-amd64
+
+install-opensuse-15.2-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-opensuse-15.2-amd64
+  image: registry.nic.cz/labs/bird:opensuse-15.2-amd64
+
+install-opensuse-15.3-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-opensuse-15.3-amd64
+  image: registry.nic.cz/labs/bird:opensuse-15.3-amd64
+
+install-opensuse-15.4-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-opensuse-15.4-amd64
+  image: registry.nic.cz/labs/bird:opensuse-15.4-amd64
+
+install-opensuse-15.5-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-opensuse-15.5-amd64
+  image: registry.nic.cz/labs/bird:opensuse-15.5-amd64
+
+install-fedora-34-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-34-amd64
+  image: registry.nic.cz/labs/bird:fedora-34-amd64
+
+install-fedora-35-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-35-amd64
+  image: registry.nic.cz/labs/bird:fedora-35-amd64
+
+install-fedora-36-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-36-amd64
+  image: registry.nic.cz/labs/bird:fedora-36-amd64
+
+install-fedora-37-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-37-amd64
+  image: registry.nic.cz/labs/bird:fedora-37-amd64
+
+install-fedora-38-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-38-amd64
+  image: registry.nic.cz/labs/bird:fedora-38-amd64
+
+install-fedora-39-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-39-amd64
+  image: registry.nic.cz/labs/bird:fedora-39-amd64
+
+install-fedora-40-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-40-amd64
+  image: registry.nic.cz/labs/bird:fedora-40-amd64
+
+install-fedora-41-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-41-amd64
+  image: registry.nic.cz/labs/bird:fedora-41-amd64
+
+install-fedora-42-amd64:
+  <<: *install-rpm
+  needs:
+    - job: pkg-fedora-42-amd64
+  image: registry.nic.cz/labs/bird:fedora-42-amd64
+
+install-ubuntu-18.04-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-ubuntu-18.04-amd64
+  image: registry.nic.cz/labs/bird:ubuntu-18.04-amd64
+
+install-debian-10-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-10-amd64
+  image: registry.nic.cz/labs/bird:debian-10-amd64
+
+install-debian-10-i386:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-10-i386
+  image: registry.nic.cz/labs/bird:debian-10-i386
+
+install-debian-11-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-11-amd64
+  image: registry.nic.cz/labs/bird:debian-11-amd64
+
+install-debian-11-i386:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-11-i386
+  image: registry.nic.cz/labs/bird:debian-11-i386
+
+install-debian-12-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-12-amd64
+  image: registry.nic.cz/labs/bird:debian-12-amd64
+
+install-debian-12-i386:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-12-i386
+  image: registry.nic.cz/labs/bird:debian-12-i386
+
+install-debian-testing-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-testing-amd64
+  image: registry.nic.cz/labs/bird:debian-testing-amd64
+
+install-debian-testing-i386:
+  <<: *install-deb
+  needs:
+    - job: pkg-debian-testing-i386
+  image: registry.nic.cz/labs/bird:debian-testing-i386
+
+install-ubuntu-20.04-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-ubuntu-20.04-amd64
+  image: registry.nic.cz/labs/bird:ubuntu-20.04-amd64
+
+install-ubuntu-22.04-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-ubuntu-22.04-amd64
+  image: registry.nic.cz/labs/bird:ubuntu-22.04-amd64
+
+install-ubuntu-24.04-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-ubuntu-24.04-amd64
+  image: registry.nic.cz/labs/bird:ubuntu-24.04-amd64
+
+install-ubuntu-24.10-amd64:
+  <<: *install-deb
+  needs:
+    - job: pkg-ubuntu-24.10-amd64
   image: registry.nic.cz/labs/bird:ubuntu-24.10-amd64
 
 
