fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! CI: test multikey install, part 1

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -84,6 +84,43 @@ tag-collect:
 
 ## Package installability checks
 
+.install-suse: &install-suse
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now and no user or group bird exists
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: BIRD unexpectedly installed"
+        exit 1
+      fi
+      if id -g bird >/dev/null 2>&1; then
+        echo "Error: User group 'bird' exist before installation"
+        exit 1
+      fi
+      if id -u bird >/dev/null 2>&1; then
+        echo "Error: User 'bird' exist before installation"
+        exit 1
+      fi
+    # install packages
+    - zypper in -y curl openssl ca-certificates strace
+#    - openssl s_client -showcerts -connect branch.www.bird.office.nic.cz:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > office.crt
+    - curl -k https://branch.www.bird.office.nic.cz/cznic.crt --output cznic.crt
+    - curl -k https://branch.www.bird.office.nic.cz/servers.crt --output servers.crt
+    - trust anchor cznic.crt
+    - trust anchor servers.crt
+    - curl $REPO_URL > bird.repo
+    - curl https://branch.www.bird.office.nic.cz/maria.gpg > /etc/pki/rpm-gpg/bird-maria.gpg
+    - curl https://branch.www.bird.office.nic.cz/meow.gpg > /etc/pki/rpm-gpg/bird-meow.gpg
+    - zypper ar bird.repo
+    - zypper search bird
+    - strace -o str -ff $INSTALL
+    # test that installation is successful
+    - ./tools/test-install "$CI_COMMIT_MESSAGE"
+  artifacts:
+    paths:
+      - 'str.*'
+
 .install-rpm: &install-rpm
   <<: *test-job
   stage: install
@@ -103,7 +140,7 @@ tag-collect:
         exit 1
       fi
     # install packages
-    - $PREINSTALL
+    - yum install -y openssl ca-certificates strace
     - openssl s_client -showcerts -connect branch.www.bird.office.nic.cz:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > /etc/pki/ca-trust/source/anchors/office.crt
     - curl -k https://branch.www.bird.office.nic.cz/cznic.crt --output /etc/pki/ca-trust/source/anchors/cznic.crt
     - curl -k https://branch.www.bird.office.nic.cz/servers.crt --output /etc/pki/ca-trust/source/anchors/servers.crt
@@ -111,8 +148,8 @@ tag-collect:
     - curl $REPO_URL > bird.repo
     - curl https://branch.www.bird.office.nic.cz/maria.gpg > /etc/pki/rpm-gpg/bird-maria.gpg
     - curl https://branch.www.bird.office.nic.cz/meow.gpg > /etc/pki/rpm-gpg/bird-meow.gpg
-    - $ADDREPO
-    - $LIST
+    - cp bird.repo /etc/yum.repos.d/bird.repo
+    - yum list bird
     - strace -o str -ff $INSTALL
     # test that installation is successful
     - ./tools/test-install "$CI_COMMIT_MESSAGE"
@@ -125,189 +162,132 @@ install-centos-7-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:centos-7-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/centos/7/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.el7
 
 install-centos-8-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:centos-8-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/centos/8/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.el8
 
 install-rocky-08-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:rocky-08-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/rocky/08/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.el8
 
 install-rocky-09-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:rocky-09-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/rocky/09/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.el9
 
 install-opensuse-15.0-amd64:
-  <<: *install-rpm
+  <<: *install-suse
   image: registry.nic.cz/labs/bird:opensuse-15.0-amd64
   variables:
-    PREINSTALL: zypper in -y curl openssl ca-certificates strace
-    ADDREPO: zypper ar bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/opensuse/15.0/x86_64/bird.repo
-    LIST: zypper search bird
     INSTALL: zypper in -y bird=3.1.5-cznic.1
 
 install-opensuse-15.1-amd64:
-  <<: *install-rpm
+  <<: *install-suse
   image: registry.nic.cz/labs/bird:opensuse-15.1-amd64
   variables:
-    PREINSTALL: zypper in -y curl openssl ca-certificates strace
-    ADDREPO: zypper ar bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/opensuse/15.1/x86_64/bird.repo
-    LIST: zypper search bird
     INSTALL: zypper in -y bird=3.1.5-cznic.1
 
 install-opensuse-15.2-amd64:
-  <<: *install-rpm
+  <<: *install-suse
   image: registry.nic.cz/labs/bird:opensuse-15.2-amd64
   variables:
-    PREINSTALL: zypper in -y curl openssl ca-certificates strace
-    ADDREPO: zypper ar bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/opensuse/15.2/x86_64/bird.repo
-    LIST: zypper search bird
     INSTALL: zypper in -y bird=3.1.5-cznic.1
 
 install-opensuse-15.3-amd64:
-  <<: *install-rpm
+  <<: *install-suse
   image: registry.nic.cz/labs/bird:opensuse-15.3-amd64
   variables:
-    PREINSTALL: zypper in -y curl openssl ca-certificates strace
-    ADDREPO: zypper ar bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/opensuse/15.3/x86_64/bird.repo
-    LIST: zypper search bird
     INSTALL: zypper in -y bird=3.1.5-cznic.1
 
 install-opensuse-15.4-amd64:
-  <<: *install-rpm
+  <<: *install-suse
   image: registry.nic.cz/labs/bird:opensuse-15.4-amd64
   variables:
-    PREINSTALL: zypper in -y curl openssl ca-certificates strace
-    ADDREPO: zypper ar bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/opensuse/15.4/x86_64/bird.repo
-    LIST: zypper search bird
     INSTALL: zypper in -y bird=3.1.5-cznic.1
 
 install-opensuse-15.5-amd64:
-  <<: *install-rpm
+  <<: *install-suse
   image: registry.nic.cz/labs/bird:opensuse-15.5-amd64
   variables:
-    PREINSTALL: zypper in -y curl openssl ca-certificates strace
-    ADDREPO: zypper ar bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/opensuse/15.5/x86_64/bird.repo
-    LIST: zypper search bird
     INSTALL: zypper in -y bird=3.1.5-cznic.1
 
 install-fedora-34-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-34-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/34/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc34
 
 install-fedora-35-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-35-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/35/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc35
 
 install-fedora-36-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-36-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/36/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc36
 
 install-fedora-37-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-37-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/37/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc37
 
 install-fedora-38-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-38-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/38/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc38
 
 install-fedora-39-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-39-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/39/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc39
 
 install-fedora-40-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-40-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/40/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc40
 
 install-fedora-41-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-41-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/41/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc41
 
 install-fedora-42-amd64:
   <<: *install-rpm
   image: registry.nic.cz/labs/bird:fedora-42-amd64
   variables:
-    PREINSTALL: yum install -y openssl ca-certificates strace
-    ADDREPO: cp bird.repo /etc/yum.repos.d/bird.repo
     REPO_URL: https://branch.www.bird.office.nic.cz/fedora/42/x86_64/bird.repo
-    LIST: yum list bird
     INSTALL: yum install -y bird-3.1.5-cznic.1.fc42
 
diff --git a/misc/gitlab/template.yml.j2 b/misc/gitlab/template.yml.j2
--- a/misc/gitlab/template.yml.j2
+++ b/misc/gitlab/template.yml.j2
@@ -84,6 +84,43 @@ tag-collect:
 
 ## Package installability checks
 
+.install-suse: &install-suse
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now and no user or group bird exists
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: BIRD unexpectedly installed"
+        exit 1
+      fi
+      if id -g bird >/dev/null 2>&1; then
+        echo "Error: User group 'bird' exist before installation"
+        exit 1
+      fi
+      if id -u bird >/dev/null 2>&1; then
+        echo "Error: User 'bird' exist before installation"
+        exit 1
+      fi
+    # install packages
+    - zypper in -y curl openssl ca-certificates strace
+#    - openssl s_client -showcerts -connect branch.www.bird.office.nic.cz:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > office.crt
+    - curl -k https://branch.www.bird.office.nic.cz/cznic.crt --output cznic.crt
+    - curl -k https://branch.www.bird.office.nic.cz/servers.crt --output servers.crt
+    - trust anchor cznic.crt
+    - trust anchor servers.crt
+    - curl $REPO_URL > bird.repo
+    - curl https://branch.www.bird.office.nic.cz/maria.gpg > /etc/pki/rpm-gpg/bird-maria.gpg
+    - curl https://branch.www.bird.office.nic.cz/meow.gpg > /etc/pki/rpm-gpg/bird-meow.gpg
+    - zypper ar bird.repo
+    - zypper search bird
+    - strace -o str -ff $INSTALL
+    # test that installation is successful
+    - ./tools/test-install "$CI_COMMIT_MESSAGE"
+  artifacts:
+    paths:
+      - 'str.*'
+
 .install-rpm: &install-rpm
   <<: *test-job
   stage: install
@@ -103,7 +140,7 @@ tag-collect:
         exit 1
       fi
     # install packages
-    - $PREINSTALL
+    - yum install -y openssl ca-certificates strace
     - openssl s_client -showcerts -connect branch.www.bird.office.nic.cz:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > /etc/pki/ca-trust/source/anchors/office.crt
     - curl -k https://branch.www.bird.office.nic.cz/cznic.crt --output /etc/pki/ca-trust/source/anchors/cznic.crt
     - curl -k https://branch.www.bird.office.nic.cz/servers.crt --output /etc/pki/ca-trust/source/anchors/servers.crt
@@ -111,9 +148,8 @@ tag-collect:
     - curl $REPO_URL > bird.repo
     - curl https://branch.www.bird.office.nic.cz/maria.gpg > /etc/pki/rpm-gpg/bird-maria.gpg
     - curl https://branch.www.bird.office.nic.cz/meow.gpg > /etc/pki/rpm-gpg/bird-meow.gpg
-    - $ADDREPO
-{#-    - $REPOLIST #}
-    - $LIST
+    - cp bird.repo /etc/yum.repos.d/bird.repo
+    - yum list bird
     - strace -o str -ff $INSTALL
     # test that installation is successful
     - ./tools/test-install "$CI_COMMIT_MESSAGE"
@@ -123,18 +159,9 @@ tag-collect:
 
 {% for dist in distros %}{% if "rpm" in dist["type"] %}
 install-{{ dist["name"] }}:
-  <<: *{{ {
-    "pkg-rpm": "install-rpm",
-    "pkg-rpm-wa": "install-rpm",
-    "pkg-deb": "install-deb",
-    "pkg-deb-legacy": "install-deb",
-  }[dist["type"]] }}
+  <<: *{% if "opensuse" in dist["name"] %}install-suse{% else %}install-rpm{% endif %}
   image: registry.nic.cz/labs/bird:{{ dist["name"] }}
   variables:
-    PREINSTALL: {% if "opensuse" in dist["name"] %}zypper in -y curl openssl ca-certificates strace{% else %}yum install -y openssl ca-certificates strace{% endif %}
-    ADDREPO: {% if "opensuse" in dist["name"] %}zypper ar bird.repo{% else %}cp bird.repo /etc/yum.repos.d/bird.repo{% endif %}
     REPO_URL: {{ dist["branchrepo"] }}
-{#-    REPOLIST: {% if "opensuse" in dist["name"] %}zypper lr{% else %}yum repolist -v{% endif %} #}
-    LIST: {% if "opensuse" in dist["name"] %}zypper search bird{% else %}yum list bird{% endif %}
     INSTALL: {% if "opensuse" in dist["name"] %}zypper in -y bird=3.1.5-cznic.1{% else %}yum install -y bird-3.1.5-cznic.1{{ dist["vsuf"] }}{% endif %}
 {% endif %}{% endfor %}
