CI: Add package install tests.
We are checking that generated BIRD packages can be installed and run.
Communication between bird and birdc is also tested.

diff --git a/misc/gitlab/template.yml.j2 b/misc/gitlab/template.yml.j2
--- a/misc/gitlab/template.yml.j2
+++ b/misc/gitlab/template.yml.j2
@@ -23,6 +23,7 @@ stages:
   - image
   - build
   - pkg
+  - install
   - test
 
 ## Common rules
@@ -242,7 +243,6 @@ build-release:
     - if python3 -m venv venv; then . venv/bin/activate; fi
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.deb
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -260,7 +260,6 @@ build-release:
     - pip3 install beautifulsoup4==4.11.2
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.deb
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -272,7 +271,6 @@ build-release:
   script:
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.rpm
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -287,7 +285,6 @@ build-release:
     - pip3 install beautifulsoup4==4.11.2
     - pip3 install apkg
     - apkg build -a bird-$(cat VERSION)*.tar.gz
-    #- apkg install -y pkg/pkgs/*/*/*.rpm
   artifacts:
     paths:
       - pkg/pkgs/*
@@ -306,6 +303,51 @@ pkg-{{ dist["name"] }}:
   variables:
 {{ dist["variables"] | to_yaml | indent(4, true) }}
 {%- endif %}
+{% endfor %}
+
+## Package installability checks
+
+.install-deb: &install-deb
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: bird unexpectedly installed"
+        exit 1
+      fi
+    # install packages
+    - find pkg/pkgs/ -type f -name '*.deb' '(' -ls -exec dpkg -i '{}' ';' ')'
+    # test that install is correct
+    - ./tools/test-install "$CI_COMMIT_MESSAGE"
+
+.install-rpm: &install-rpm
+  <<: *test-job
+  stage: install
+  script:
+    # check that bird is _not_ installed now
+    - |
+      if bird --version >/dev/null 2>&1; then
+        echo "Error: bird unexpectedly installed"
+        exit 1
+      fi
+    # install packages
+    - find pkg/pkgs/ -type f -name '*.rpm' '(' -ls -exec rpm -i '{}' ';' ')'
+    # test that install is correct
+    - ./tools/test-install "$CI_COMMIT_MESSAGE"
+
+{% for dist in distros %}
+install-{{ dist["name"] }}:
+  <<: *{{ {
+    "pkg-rpm": "install-rpm",
+    "pkg-rpm-wa": "install-rpm",
+    "pkg-deb": "install-deb",
+    "pkg-deb-legacy": "install-deb",
+  }[dist["type"]] }}
+  needs:
+    - job: pkg-{{ dist["name"] }}
+  image: registry.nic.cz/labs/bird:{{ dist["name"] }}
 {% endfor %}
 
 ###################################
