Make: Single entry point, multiple build profiles
It has been annoying to always run ./configure and make. Now one just
runs make and it (re)configures itself automatically whenever needed.
Also the INSTALL file has been updated, and the release machinery as
well.

It's now possible to define build profiles with different configure
options, and keep these builds separate. For now, there are three of
them:

- debug (regular build from Git)
- release (regular build from TGZ)
- deb (when building DEB packages)

Building RPM is broken here, gonna check later. (This is expected to fail in Gitlab.)

diff --git a/tools/make-archive b/tools/make-archive
--- a/tools/make-archive
+++ b/tools/make-archive
@@ -15,10 +15,6 @@ VERSION="$($(dirname $0)/version | sed 's/^v//')"
 SRCPKG="bird-${VERSION}"
 DOCPKG="bird-doc-${VERSION}"
 
-if [ -z "$ARCHIVE_DOCS" ]; then
-  ARCHIVE_DOCS=true
-fi
-
 # Check that we are running on a clean repository
 if ! git diff-index --quiet HEAD || ! git diff-index --cached --quiet HEAD; then
   echo 'WARNING: git index has uncommitted changes!'
@@ -64,12 +60,15 @@ pushd $T
     rm -rf rfc doc/slides doc/slt2001 doc/old bird.conf
 
     # Fix the version string
-    sed -i 's/^VERSION := .*/VERSION := '${VERSION}'/' Makefile.in
+    sed -i 's/^VERSION :=$/VERSION := '${VERSION}'/' Makefile
+
+    # Default target is release
+    sed -i 's/^DEFAULT_TARGET := .*$/DEFAULT_TARGET := release/' Makefile
 
     # Run autoconf
     echo "Running autoreconf"
-    autoreconf -i
-    rm -rf autom4te*cache
+    make configure
+    make autoconf-clean
 
   popd
 
@@ -77,35 +76,30 @@ pushd $T
   echo "Packing source package"
   stabletgz $SRCPKG.tar.gz $SRCPKG
 
-  if $ARCHIVE_DOCS; then
-    # Generate documentation
-    pushd $SRCPKG
-      # Fix documentation in time
-      sed -i "s#^<date></date>#<date>$COMMIT_DATE</date>#" doc/bird.sgml
-      sed -i "s#^</documentid>#-$HEAD</documentid>#" doc/bird.sgml
+  # Generate documentation
+  pushd $SRCPKG
+    # Fix documentation in time
+    sed -i "s#^<date></date>#<date>$COMMIT_DATE</date>#" doc/bird.sgml
+    sed -i "s#^</documentid>#-$HEAD</documentid>#" doc/bird.sgml
 
-      # Actually make it
-      echo "Creating documentation"
-      (./configure --with-protocols= --disable-client && make docs) > build.log 2>build.err || (
-	echo "======== Build log ========"
-	cat build.log
-	echo "======== Error log ========"
-	cat build.err
-	echo "If you wish to not build documentation, set env ARCHIVE_DOCS=false"
-	false
-      )
-    popd
+    # Actually make it
+    echo "Creating documentation"
+    (make docs) > build.log 2>build.err || (
+      echo "======== Build log ========"
+      cat build.log
+      echo "======== Error log ========"
+      cat build.err
+      echo "If you wish to not build documentation, set env ARCHIVE_DOCS=false"
+      false
+    )
+  popd
 
-    mkdir ${DOCPKG}{,/doc}
-    cp $SRCPKG/obj/doc/*.{html,pdf} ${DOCPKG}/doc
+  mkdir ${DOCPKG}{,/doc}
+  cp $SRCPKG/build/release/doc/*.{html,pdf} ${DOCPKG}/doc
 
-    # Pack sources
-    echo "Packing docs package"
-    stabletgz $DOCPKG.tar.gz $DOCPKG
-  else
-    echo "Skipping documentation build"
-  fi
-
+  # Pack sources
+  echo "Packing docs package"
+  stabletgz $DOCPKG.tar.gz $DOCPKG
 popd
 
 if $ARCHIVE_DOCS; then
